export class ProductsActions {

  static SUBSCRIBE_PRODUCTS = 'SUBSCRIBE_PRODUCTS';
  static SUBSCRIBE_PRODUCTS_SUCCESS = 'SUBSCRIBE_PRODUCTS_SUCCESS';
  static SUBSCRIBE_PRODUCTS_FAIL = 'SUBSCRIBE_PRODUCTS_FAIL';

  static UNSUBSCRIBE_PRODUCTS = 'UNSUBSCRIBE_PRODUCTS';

  static INSERT_PRODUCT = 'INSERT_PRODUCT';
  static INSERT_PRODUCT_SUCCESS = "INSERT_PRODUCT_SUCCESS";
  static INSERT_PRODUCT_FAIL = "INSERT_PRODUCT_FAIL";

  static UPDATE_PRODUCT = 'UPDATE_PRODUCT';
  static UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
  static UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

  static REMOVE_PRODUCT = 'REMOVE_PRODUCT';
  static REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
  static REMOVE_PRODUCT_FAIL = 'REMOVE_PRODUCT_FAIL';


  static PRODUCTS_SYNCED = 'PRODUCTS_SYNCED';

  static PRODUCTS_UNSUBSCRIBED = 'PRODUCTS_UNSUBSCRIBED';
}